version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: "weekly"
    time: "08:00"
    day: "saturday"
    timezone: Asia/Jakarta
  open-pull-requests-limit: 100
  groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: "weekly"
    time: "08:00"
    day: "saturday"
    timezone: Asia/Jakarta
  open-pull-requests-limit: 100
