on:
  push:
    tags:
      - @berviantoleo/react-multi-crop@*
env:
  CI: true
  NODE_VERSION: 14.x
  GITHUB_NPM: https://npm.pkg.github.com/
  NPM_SITE: https://registry.npmjs.org
  SCOPE: '@berviantoleo'
jobs:
  release:
    name: NPM Release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: ${{ env.GITHUB_NPM }}
          scope: ${{ env.SCOPE }}
          always-auth: true
      - name: Restore lerna
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: |
          yarn --frozen-lockfile
          yarn bootstrap
      - name: Build Package
        run: |
          yarn lerna run build --scope @berviantoleo/react-multi-crop
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: ${{ env.NPM_SITE }}
          scope: ${{ env.SCOPE }}
          always-auth: true
      - name: Publish to NPM
        run: yarn publish packages/react-multi-crop --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}