name: Test & Build
on:
  pull_request:
    branches:
      - main
env:
  CI: true
jobs:
  test:
    name: Test and Build (${{ matrix.node_version }})
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node_version:
          - 18
          - 19
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js (${{ matrix.node_version }})
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          always-auth: true
      - name: Restore lerna
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            */*/node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-${{ matrix.node_version }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: |
          yarn --frozen-lockfile
          yarn bootstrap
      - name: Lint
        run: yarn lint
      - name: Test & Build Package
        run: |
          yarn lerna run test --scope @berviantoleo/react-multi-crop
          yarn lerna run build --scope @berviantoleo/react-multi-crop
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: yarn start
          wait-on: 'http://localhost:3000'
          working-directory: examples/demo
        env:
          SKIP_PREFLIGHT_CHECK: true
      - name: Upload to Codecov
        uses: codecov/codecov-action@v3
