name: Test & Build
on:
  pull_request:
    branches:
      - main
env:
  CI: true
jobs:
  test:
    name: Test and Build (${{ matrix.node_version }})
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        node_version:
          - 22
          - 24
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Setup Node.js (${{ matrix.node_version }})
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node_version }}
          always-auth: true
      - name: Restore lerna
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            */*/node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-${{ matrix.node_version }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: corepack enable && corepack prepare yarn@stable --activate && yarn --immutable
      - name: Lint
        run: yarn lint
      - name: Test & Build Package
        run: |
          yarn lerna run test --scope @berviantoleo/react-multi-crop
          yarn lerna run build --scope @berviantoleo/react-multi-crop
      - name: Try Build Docs
        run: |
          yarn docs
          yarn lerna run docs --scope @berviantoleo/react-multi-crop
      - name: Try Build Demo
        run: yarn lerna run build --scope @berviantoleo/react-multi-crop-demo
        env:
          SKIP_PREFLIGHT_CHECK: true
          PUBLIC_URL: /
          DISABLE_ESLINT_PLUGIN: true
      # TODO; will give the docs to artifacts
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: yarn start
          wait-on: 'http://localhost:3000'
          working-directory: examples/demo
        env:
          SKIP_PREFLIGHT_CHECK: true
      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # required
